#!/usr/bin/env ruby

CALLER_DIR = %x(pwd)
# Dir.chdir('')

require 'pp'
require_relative 'soxbot_lib/sox.rb'
require_relative 'soxbot_lib/params.rb'

sox = Sox.new

ans = sox.files_selector_prompt ARGV
# we should: abort unless ans # but it's not working
cmds = sox.commands_selector_prompt
